const karyawan = [
{id:1,name:'HJ.Yati Rohayati, S.ST',jabatan:'Bidan Desa Sindangsuka',ruangan:'Pelayanan Pemeriksaan Ibu Hamil',photo:'karyawan/yati.jpg'},
{id:2,name:'HJ.Yanti Widayanti, S.ST',jabatan:'Koordinator Unit KESGA (UKP)',ruangan:'Pelayanan Pemeriksaan Ibu Hamil',photo:'karyawan/yanti.jpg'},
{id:3,name:'Wari, S.ST',jabatan:'Koordinator Unit PONED',ruangan:'',photo:'karyawan/wari.jpg'},
{id:4,name:'H. Maman, SKM., S.Kep., Ners',jabatan:'PJ Klaster IV',ruangan:'Pelayanan Usia Produktif',photo:'karyawan/maman.jpg'},
{id:5,name:'Titin Rustini, S.Tr.Keb',jabatan:'Pelaksana Kesga UKP & Program Hepatitis',ruangan:'Pelayanan Pemeriksaan Ibu Hamil',photo:'karyawan/titin.jpg'},
{id:6,name:'Eneng Sri Ratna Komala Dewi, S.Tr.Keb',jabatan:'Bidan Desa Padasuka',ruangan:'',photo:'karyawan/eneng.jpg'},
{id:7,name:'H.Ajat Sudrajat Haryadi,S.Kep.,Ners',jabatan:'Kepala Puskesmas',ruangan:'',photo:'karyawan/ajat.jpg'},
{id:8,name:'Darmini, S.Kep',jabatan:'Kepala Pustu Desa Kertajaya',ruangan:'',photo:'karyawan/darmini.jpg'},
{id:9,name:'H. Wawan Irawan, S.Kep',jabatan:'Koordinator MFK',ruangan:'',photo:'karyawan/wawan.jpg'},
{id:10,name:'Epi Saepul Hardi, S.Kep',jabatan:'Kepala Pustu Desa Sindangsuka',ruangan:'',photo:'karyawan/epi.jpg'},
{id:11,name:'Atang Suhara, AMKG',jabatan:'Pelaksana Unit Kesgimul',ruangan:'',photo:'karyawan/atang.jpg'},
{id:12,name:'Hj.Inoh, S.ST',jabatan:'Bidan Desa Girimukti',ruangan:'',photo:'karyawan/inoh.jpg'},
{id:13,name:'Erwin Kurniawan, S.Kep',jabatan:'Kasubag Tata Usaha',ruangan:'',photo:'karyawan/erwin.jpg'},
{id:14,name:'dr. Dini Aditya M',jabatan:'PJ Mutu',ruangan:'',photo:'karyawan/dini.jpg'},
{id:15,name:'drg. Sofiatina',jabatan:'Koordinator Unit Kesgimul & Koord PPI',ruangan:'',photo:'karyawan/sofiatina.jpg'},
{id:16,name:'Tuti Susilawati, S.Si',jabatan:'Pengadministrasi Umum',ruangan:'',photo:'karyawan/tuti.jpg'},
{id:17,name:'Dyah Rahmawati, S.Kep.Ners',jabatan:'Pelaksana Program Kes. Jiwa',ruangan:'',photo:'karyawan/dyah.jpg'},
{id:18,name:'Noli Rofyati, S.Tr.Keb',jabatan:'Bidan Desa Cibunar',ruangan:'',photo:'karyawan/noli.jpg'},
{id:19,name:'Elfira Ranti Handayani, S.Keb.',jabatan:'Koordinator KESGA UKM & Bidan Desa Kertajaya',ruangan:'',photo:'karyawan/elfira.jpg'},
{id:20,name:'Mira Rahmi Utami, S.Keb.',jabatan:'Bidan Desa Cibatu',ruangan:'',photo:'karyawan/mira.jpg'},
{id:21,name:'dr. Ika Kusumawati',jabatan:'PJ UKP Kefarmasian & Laboratorium',ruangan:'',photo:'karyawan/ika.jpg'},
{id:22,name:'Fikka Amalia, SKM',jabatan:'PJ UKM Esensial',ruangan:'',photo:'karyawan/fikka.jpg'},
{id:23,name:'Gima Amelia Sari,S.Farm,Apt.',jabatan:'Pelaksana Apotek',ruangan:'',photo:'karyawan/gima.jpg'},
{id:24,name:'Nur Asiah,S.Kep.,Ners',jabatan:'Koordinator Unit Rawat Inap',ruangan:'',photo:'karyawan/nur.jpg'},
{id:25,name:'Siska Mariana, S.Tr.Keb',jabatan:'Bidan Desa Sukalilah / Bendahara',ruangan:'',photo:'karyawan/siska.jpg'},
{id:26,name:'Iis Ismawati, AMd.Kep',jabatan:'Pelaksana Unit Rawat Jalan / PPI',ruangan:'',photo:'karyawan/iis.jpg'},
{id:27,name:'Resna Rahayu, S.Tr.Keb',jabatan:'Bidan',ruangan:'',photo:'karyawan/resna.jpg'},
{id:28,name:'Leni Indriani, S.Kep., Ners',jabatan:'Pelaksana Perawat Rawat Inap',ruangan:'',photo:'karyawan/leni.jpg'},
{id:29,name:'Devi Oktaviani, A.Md.Keb',jabatan:'Bidan Desa Keresek',ruangan:'',photo:'karyawan/devi.jpg'},
{id:30,name:'Teni Denawati, A.Md.Keb',jabatan:'Bidan Desa Mekarmukti',ruangan:'',photo:'karyawan/teni.jpg'},
{id:31,name:'Tintin Supriatin, S.Keb.',jabatan:'Bidan Desa Wanakerta',ruangan:'',photo:'karyawan/tintin.jpg'},
{id:32,name:'Eten Saripudin, S.Kep.,Ners',jabatan:'Pengadministrasi Sarpras',ruangan:'',photo:'karyawan/eten.jpg'},
{id:33,name:'Widya Rahma Talitha, A.Md.KG',jabatan:'Pelaksana Kesgimul / Barjas',ruangan:'',photo:'karyawan/widya.jpg'},
{id:34,name:'Irpan Firmansah, Amd.Kep',jabatan:'Pelaksana Perawat UGD / Kes. Indera',ruangan:'',photo:'karyawan/irpan.jpg'},
{id:35,name:'Yan Yan Pelawati, A.md. Kep.',jabatan:'Pelaksana Perawat Rawat Inap',ruangan:'',photo:'karyawan/yan.jpg'},
{id:36,name:'Mulya Mustikasari, S.Tr.Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/mulya.jpg'},
{id:37,name:'Ida Nurul Aprilyanti, A.Md.Kes',jabatan:'Pelaksana Kesgimul',ruangan:'',photo:'karyawan/ida.jpg'},
{id:38,name:'Erus Rustandi, A.Md.Kep',jabatan:'Pelaksana Perawat / Program TB Paru',ruangan:'',photo:'karyawan/erus.jpg'},
{id:39,name:'Dini Auliani Karmana, A.Md.AK',jabatan:'Pelaksana Laboratorium Kesehatan',ruangan:'',photo:'karyawan/dini.jpg'},
{id:40,name:'Kurnia Putri Mardanti, A.Md.Gz',jabatan:'Gizi (UKP)',ruangan:'',photo:'karyawan/kurnia.jpg'},
{id:41,name:'Depi Nurhayati, AMKL',jabatan:'Koordinator Kesling',ruangan:'',photo:'karyawan/depi.jpg'},
{id:42,name:'Achmad Kandarsyah, S.Si, Apt',jabatan:'Koordinator Unit Kefarmasian',ruangan:'',photo:'karyawan/achmad.jpg'},
{id:43,name:'Neng Arti Lestari, S.Kep.,Ners',jabatan:'Pelaksana Perawat Rawat Inap',ruangan:'',photo:'karyawan/neng.jpg'},
{id:44,name:'Haryadi Akbar, S.Kep.,Ners',jabatan:'Pelaksana Perawat',ruangan:'',photo:'karyawan/haryadi.jpg'},
{id:45,name:'Wandi Gumilar, S.Kep., Ners',jabatan:'Pelaksana Perawat',ruangan:'',photo:'karyawan/wandi.jpg'},
{id:46,name:'Hj. Ima Siti Mulyani, S.ST.',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/ima.jpg'},
{id:47,name:'Ai Irmawati, S.KM',jabatan:'Pelaksana Promkes',ruangan:'',photo:'karyawan/ai.jpg'},
{id:48,name:'Pipin Pirdaos, SKM',jabatan:'Pelaksana Pendfataran & Sarpras',ruangan:'',photo:'karyawan/pipin.jpg'},
{id:49,name:'Olga Oktaviani, S.Tr',jabatan:'Koordinator Rekam Medis',ruangan:'',photo:'karyawan/olga.jpg'},
{id:50,name:'Nendi Yuwansyah R, SKM',jabatan:'Adminkes',ruangan:'',photo:'karyawan/nendi.jpg'},
{id:51,name:'Irwan Sumahadi Saputra, Amd.Kep',jabatan:'Pelaksana Perawat Unit Rawat Jalan / Ka Pusku Girimukti',ruangan:'',photo:'karyawan/irwan.jpg'},
{id:52,name:'Yana Rosdiana, S.Kep., Ners',jabatan:'Koordinator Unit UGD',ruangan:'',photo:'karyawan/yana.jpg'},
{id:53,name:'Nina Mariana, AMKG',jabatan:'Pelaksana Kesgimul & Program UKGM UKGS',ruangan:'',photo:'karyawan/nina.jpg'},
{id:54,name:'Cucu Halimatusyadiah, A.Md.keb',jabatan:'Bidan Desa Mekarsari',ruangan:'',photo:'karyawan/cucu.jpg'},
{id:55,name:'Kartika, AMK',jabatan:'Pelaksana Perawat Rawat Inap',ruangan:'',photo:'karyawan/kartika.jpg'},
{id:56,name:'Herliyanti Suherman, Amd.Keb',jabatan:'Pelaksana Bidan Kesga UKP',ruangan:'',photo:'karyawan/herliyanti.jpg'},
{id:57,name:'Rina Umayah Y, AMd.Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/rina.jpg'},
{id:58,name:'Nia Muawanah, S.Keb',jabatan:'Pelaksana Bidan MTBS',ruangan:'',photo:'karyawan/nia.jpg'},
{id:59,name:'Rani Anggraeni, A.Md.Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/rani.jpg'},
{id:60,name:'Rima Marantika, A.Md.Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/rima.jpg'},
{id:61,name:'Syarifah Aini, S.Kep.,Ners',jabatan:'Pelaksana Perawatn Rawat Inap',ruangan:'',photo:'karyawan/syarifah.jpg'},
{id:62,name:'Meta Gurnita, A.Md.Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/meta.jpg'},
{id:63,name:'Yudha Mulyanata, Amd.Kep',jabatan:'Pelaksana Perawatn Rawat Inap / Koord Surveilans',ruangan:'',photo:'karyawan/yudha.jpg'},
{id:64,name:'Agus Ramdani, S.Kep',jabatan:'Pelaksana Perawat UGD & Prog KESORGA',ruangan:'',photo:'karyawan/agus.jpg'},
{id:65,name:'Ahmad Qorni Kurniawan, Amd.Kep',jabatan:'Pelaksana Perawat UGD & Prog Kes. Kerja',ruangan:'',photo:'karyawan/ahmad.jpg'},
{id:66,name:'Santi Yulianti, Amd.Kep',jabatan:'Pelaksana Perawat Rawat Inap',ruangan:'',photo:'karyawan/santi.jpg'},
{id:67,name:'Indra Pratama, S.,Kep',jabatan:'Pelaksana Perawat UGD',ruangan:'',photo:'karyawan/indra.jpg'},
{id:68,name:'Nurul Fauziah, Amd.Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/nurul.jpg'},
{id:69,name:'Kakan Dian Herdiansyah, Amd.AK',jabatan:'Koordinator Unit Laboratorium',ruangan:'',photo:'karyawan/kakan.jpg'},
{id:70,name:'Nisa Nurfajrina, Amd. Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/nisa.jpg'},
{id:71,name:'Indah Maelani Sutadi, Amd. Kep',jabatan:'Pelaksana Perawat Rawat Inap / Program ISPA',ruangan:'',photo:'karyawan/indah.jpg'},
{id:72,name:'Hilmi Latip, Amd. Farm',jabatan:'Pelaksana Asis Apoteker',ruangan:'',photo:'karyawan/hilmi.jpg'},
{id:73,name:'Asri Purwanti, A.Md.Kep',jabatan:'Pelaksana Perawat Rawat Inap /& Program UKS',ruangan:'',photo:'karyawan/asri.jpg'},
{id:74,name:'Widia Nurani, Amd.Gz',jabatan:'Kord. Program Gizi UKM',ruangan:'',photo:'karyawan/widia.jpg'},
{id:75,name:'Atep Prasetia, Amd. Kep',jabatan:'Pelaksana Perawat UGD & Program. P2 DBD',ruangan:'',photo:'karyawan/atep.jpg'},
{id:76,name:'Maryadi, Amd. Farm',jabatan:'Pelaksana Asis Apoteker',ruangan:'',photo:'karyawan/maryadi.jpg'},
{id:77,name:'Denny Harry Purnama, Amd.Kes',jabatan:'Pelaksana Analis Kesehatan Lab',ruangan:'',photo:'karyawan/denny.jpg'},
{id:78,name:'Haqi Hilmawan Nizar, Amd.Kep',jabatan:'Pelaksana Perawat Rawat Inap',ruangan:'',photo:'karyawan/haqi.jpg'},
{id:79,name:'Indri Depani Augusta, A.Md.Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/indri.jpg'},
{id:80,name:'Asep Dehar Triana, Amd.Kep',jabatan:'Pelaksana Perawat UGD',ruangan:'',photo:'karyawan/asep.jpg'},
{id:81,name:'Resa Octora, Amd.Kes',jabatan:'Pelaksana Perekam Medis',ruangan:'',photo:'karyawan/resa.jpg'},
{id:82,name:'Intan Purnamasari, AM. Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/intan.jpg'},
{id:83,name:'Iwa Kartiwa, A.Md,Kep',jabatan:'Pelakasana Perawat UGD',ruangan:'',photo:'karyawan/iwa.jpg'},
{id:84,name:'Ai Rosmayanti, A. Md. Keb',jabatan:'Pelaksana Bidan PONED',ruangan:'',photo:'karyawan/ai.jpg'},
{id:85,name:'Rida Rindiantika, A. Md. AK',jabatan:'Pelaksana Analis Kesehatan Lab',ruangan:'',photo:'karyawan/rida.jpg'},
{id:86,name:'Salma Aulia Nur Ayu, A.Md.RMIK',jabatan:'Pelaksana Perekam Medis',ruangan:'',photo:'karyawan/salma.jpg'},
{id:87,name:'Riana Dwi Kartika, A.Md.Keb',jabatan:'Pelaksana Bidan',ruangan:'',photo:'karyawan/riana.jpg'},
{id:88,name:'Mita Karina, A.Md.Keb.',jabatan:'Pelaksana Bidan',ruangan:'',photo:'karyawan/mita.jpg'},
{id:89,name:'Nina Maria, A.Md',jabatan:'Koordinatir Kasir & Pelaksana Pendaftaran',ruangan:'',photo:'karyawan/nina.jpg'},
{id:90,name:'Nuraida Fitri',jabatan:'Pelaksana Dapur',ruangan:'',photo:'karyawan/nuraida.jpg'},
{id:91,name:'Rayi Egi Kusniawan',jabatan:'Pelaksana Pendaftaran',ruangan:'',photo:'karyawan/rayi.jpg'},
{id:92,name:'Hadi Rafi Pratama',jabatan:'Koordinator SIP',ruangan:'',photo:'karyawan/hadi.jpg'},
{id:93,name:'Ardi Nasrudin',jabatan:'Sopir Ambulance',ruangan:'',photo:'karyawan/ardi.jpg'},
{id:94,name:'Deden Kusdinar, S.Ag',jabatan:'Pelaksana Pengadministrasi Umum',ruangan:'',photo:'karyawan/deden.jpg'},
{id:95,name:'Ramdan Apriansyah',jabatan:'Teknis Komputer',ruangan:'',photo:'karyawan/ramdan.jpg'},
{id:96,name:'Reni Susinta',jabatan:'Pelaksana Dapur',ruangan:'',photo:'karyawan/reni.jpg'}
];
